### ISSUE TITLE
ERR_HTTP_INVALID_STATUS_CODE

### ISSUE THREAD

**Issue by Winters-Glade** [CathryneDelamort/stable-diffusion-image-manager#1]
Appears to load but once I navigate away from the Root folder, it instantly crashes with the following error:
```
node:_http_server:339
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^

RangeError: Invalid status code: ERR_HTTP_INVALID_STATUS_CODE
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.writeHead (node:_http_server:339:11)
    at ServerResponse._implicitHeader (node:_http_server:330:8)
    at write_ (node:_http_outgoing:907:9)
    at ServerResponse.end (node:_http_outgoing:1015:5)
    at Polka.onError (G:\stable-diffusion-webui-master\stable-diffusion-image-manager-main\node_modules\vite-plugin-mix\dist\index.js:259:6)
    at Immediate.next (G:\stable-diffusion-webui-master\stable-diffusion-image-manager-main\node_modules\vite-plugin-mix\dist\index.js:331:32)
    at Immediate.<anonymous> (G:\stable-diffusion-webui-master\stable-diffusion-image-manager-main\node_modules\express\lib\router\index.js:646:15)
    at process.processImmediate (node:internal/timers:477:21) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}

Node.js v19.7.0
```
Open to any ideas that may help. This looks like a very useful program. I'd really like to use it.

**Comment by CathryneDelamort** [comment]
Thanks for reporting this @Winters-Glade! I _think_ I got this fixed. Could you pull the latest code or do a fresh clone and let me know how it goes?
